
#ifdef D3D10_ERROR_FILE_NOT_FOUND 
#undef D3D10_ERROR_FILE_NOT_FOUND
#endif

#ifdef DXGI_STATUS_OCCLUDED 
#undef DXGI_STATUS_OCCLUDED
#endif

#ifdef DXGI_STATUS_CLIPPED 
#undef DXGI_STATUS_CLIPPED
#endif

#ifdef DXGI_STATUS_NO_REDIRECTION 
#undef DXGI_STATUS_NO_REDIRECTION
#endif

#ifdef DXGI_STATUS_NO_DESKTOP_ACCESS 
#undef DXGI_STATUS_NO_DESKTOP_ACCESS
#endif

#ifdef DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE 
#undef DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE
#endif

#ifdef DXGI_STATUS_MODE_CHANGED 
#undef DXGI_STATUS_MODE_CHANGED
#endif

#ifdef DXGI_STATUS_MODE_CHANGE_IN_PROGRESS 
#undef DXGI_STATUS_MODE_CHANGE_IN_PROGRESS
#endif

#ifdef DXGI_ERROR_INVALID_CALL 
#undef DXGI_ERROR_INVALID_CALL
#endif

#ifdef DXGI_ERROR_NOT_FOUND 
#undef DXGI_ERROR_NOT_FOUND
#endif

#ifdef DXGI_ERROR_MORE_DATA 
#undef DXGI_ERROR_MORE_DATA
#endif

#ifdef DXGI_ERROR_DEVICE_REMOVED 
#undef DXGI_ERROR_DEVICE_REMOVED
#endif


#ifdef DXGI_ERROR_UNSUPPORTED 
#undef DXGI_ERROR_UNSUPPORTED
#endif

#ifdef DXGI_ERROR_UNSUPPORTED 
#undef DXGI_ERROR_UNSUPPORTED
#endif

#ifdef DXGI_ERROR_DEVICE_HUNG 
#undef DXGI_ERROR_DEVICE_HUNG
#endif

#ifdef DXGI_ERROR_DEVICE_RESET 
#undef DXGI_ERROR_DEVICE_RESET
#endif

#ifdef DXGI_ERROR_WAS_STILL_DRAWING 
#undef DXGI_ERROR_WAS_STILL_DRAWING
#endif

#ifdef DXGI_ERROR_FRAME_STATISTICS_DISJOINT 
#undef DXGI_ERROR_FRAME_STATISTICS_DISJOINT
#endif

#ifdef DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE 
#undef DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE
#endif

#ifdef DXGI_ERROR_DRIVER_INTERNAL_ERROR 
#undef DXGI_ERROR_DRIVER_INTERNAL_ERROR
#endif

#ifdef DXGI_ERROR_NONEXCLUSIVE 
#undef DXGI_ERROR_NONEXCLUSIVE
#endif

#ifdef DXGI_ERROR_NOT_CURRENTLY_AVAILABLE 
#undef DXGI_ERROR_NOT_CURRENTLY_AVAILABLE
#endif

#ifdef DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED 
#undef DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED
#endif

#ifdef DXGI_ERROR_REMOTE_OUTOFMEMORY 
#undef DXGI_ERROR_REMOTE_OUTOFMEMORY
#endif

#ifdef D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS 
#undef D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS
#endif


#ifdef D3D11_ERROR_FILE_NOT_FOUND 
#undef D3D11_ERROR_FILE_NOT_FOUND
#endif

#ifdef D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS 
#undef D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS
#endif

#ifdef D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD 
#undef D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD
#endif

#ifdef D3D10_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS 
#undef D3D10_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS
#endif



